# DataFrame 연습

In [28]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame 
# Pandas에는 Series 와 DataFrame이라는 두 종류의 모듈을 사용한다.

In [29]:
# 정렬
# 인덱스를 정렬하는 방법
# Series의 기본 구조는 index와 그 index에 맵핑에 되는 values 값이 있다.
# Series(values 값 , index = index 값) 
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [30]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [31]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [32]:
obj.sort_values(ascending=False)

c    3
b    2
a    1
d    0
dtype: int64

In [33]:
obj ## 위에서 sort를 해줬으나 obj의 결과는 변하지 않는다.

d    0
a    1
b    2
c    3
dtype: int64

In [34]:
df = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
df

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [35]:
df.sort_index()     # alphabet 순 정렬

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [36]:
df.sort_index(axis=1)    # 열(columns)을 기준으로 정렬 
# 열을 기준으로 정렬

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [37]:
dir(df)
#df.sort_column()

['T',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_builtin_table',
 '_can_fast_transpose',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iter_column_arrays',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'a',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'b',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'c',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'd',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [38]:
df.sort_index(axis=1, ascending=False)
# 내림차순으로 정렬

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [39]:
frame = DataFrame({'b': [4,7,3,2], 'a': [4,9,2,5], 'c': [5,3,7,9]}) 
frame

   b  a  c
0  4  4  5
1  7  9  3
2  3  2  7
3  2  5  9

In [40]:
frame.sort_values(by='b')

   b  a  c
3  2  5  9
2  3  2  7
0  4  4  5
1  7  9  3

In [41]:
frame.sort_values(by='a')

   b  a  c
2  3  2  7
0  4  4  5
3  2  5  9
1  7  9  3

In [42]:
# 순위 매기기 rank
obj = Series([100, 23, 99, 33])
obj.rank(ascending=False)

0    1.0
1    4.0
2    2.0
3    3.0
dtype: float64

In [43]:
obj = Series([100, 33, 99, 33])
obj.rank(ascending=False)
# 동점이 있으면 평균값을 준다

0    1.0
1    3.5
2    2.0
3    3.5
dtype: float64

In [44]:
obj.rank(method='first', ascending=False)
# 동일한 값이 존재 할 경우 먼저 나타나는 것에게 높은 순위를 줄 수 있다

0    1.0
1    3.0
2    2.0
3    4.0
dtype: float64

In [45]:
df = DataFrame({'b': [4,7,3,2], 'a': [4,9,2,5], 'c': [5,3,7,9]})
df

   b  a  c
0  4  4  5
1  7  9  3
2  3  2  7
3  2  5  9

In [46]:
df.rank(ascending=False)

     b    a    c
0  2.0  3.0  3.0
1  1.0  1.0  4.0
2  3.0  4.0  2.0
3  4.0  2.0  1.0

In [47]:
df.rank(axis=1) #행 기준으로 rank를 수행

     b    a    c
0  1.5  1.5  3.0
1  2.0  3.0  1.0
2  2.0  1.0  3.0
3  1.0  2.0  3.0

In [48]:
# NaN이 있는 경우 빼고 계산한다
df = DataFrame({'b': [4, 7, 3, 2], 'a': [4,9,2,5], 'c': [5,3,7,np.nan]})
df

   b  a    c
0  4  4  5.0
1  7  9  3.0
2  3  2  7.0
3  2  5  NaN

In [49]:
print(df.sum())
print(df.mean())

b    16.0
a    20.0
c    15.0
dtype: float64
b    4.0
a    5.0
c    5.0
dtype: float64

In [50]:
df.sum(skipna=False)
# NaN이 있으면 이를 반영하여 스킵하지 않는다
# skipna 은 skip NaN을 뜻함.

b    16.0
a    20.0
c     NaN
dtype: float64

In [51]:
df

   b  a    c
0  4  4  5.0
1  7  9  3.0
2  3  2  7.0
3  2  5  NaN

In [52]:
df.max()

b    7.0
a    9.0
c    7.0
dtype: float64

In [53]:
# 최대치, 최소치가 있는 위치를 반환한다
print(df.idxmax(), df.idxmin())

b    1
a    1
c    2
dtype: int64 b    3
a    2
c    1
dtype: int64

In [54]:
# 항목 갯수 세기

# 유니크한 값 찾기 (set)
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [55]:
set(obj)

{'a', 'b', 'c', 'd'}

In [56]:
uniques = obj.unique()   ## value 값의 종류를 확인 할 수 있다.
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [57]:
# 빈도수를 간단히 알 수 있다. 빈도수가 높은 순으로 정렬된다.
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [58]:
# 빈도수와 관련없이 나타나는 순서대로 보려면
obj.value_counts(sort=False)

b    2
c    3
a    3
d    1
dtype: int64

In [59]:
# 특정한 내용이 들어있는지 알려면 isin()을 사용한다
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [60]:
obj.isin(['b', 'c']).sum()

5

In [61]:
obj
# obj 값 확인

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [62]:
obj[mask] ## obj에서 mask 값이 true인 값만을 출력

0    c
5    b
6    b
7    c
8    c
dtype: object

In [63]:
# 아래는 같은 결과를 얻는다
obj[obj.isin(['b', 'c'])]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [64]:
df = DataFrame({'X':['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'], 
                  'Y':['f', 'g', 'd', 'g', 'h', 'e', 'd', 'h', 'f'],
                   'Z':['a', 'e', 'd', 'g', 'd', 'e', 'q', 'b', 'c']})
df

   X  Y  Z
0  c  f  a
1  a  g  e
2  d  d  d
3  a  g  g
4  a  h  d
5  b  e  e
6  b  d  q
7  c  h  b
8  c  f  c

In [65]:
df.apply(lambda s: s.value_counts())    # same as the below

     X    Y    Z
a  3.0  NaN  1.0
b  2.0  NaN  1.0
c  3.0  NaN  1.0
d  1.0  2.0  2.0
e  NaN  1.0  2.0
f  NaN  2.0  NaN
g  NaN  2.0  1.0
h  NaN  2.0  NaN
q  NaN  NaN  1.0

In [66]:
# 각 항목이 들어 있는 갯수를 센다. 없는 값은 NaN으로 표시된다
result = df.apply(pd.value_counts)
result

     X    Y    Z
a  3.0  NaN  1.0
b  2.0  NaN  1.0
c  3.0  NaN  1.0
d  1.0  2.0  2.0
e  NaN  1.0  2.0
f  NaN  2.0  NaN
g  NaN  2.0  1.0
h  NaN  2.0  NaN
q  NaN  NaN  1.0

In [67]:
# 없는 값에 0을 대입한다
result = df.apply(pd.value_counts).fillna(0) ## fillna 은 fill NaN을 뜻한다.
result

     X    Y    Z
a  3.0  0.0  1.0
b  2.0  0.0  1.0
c  3.0  0.0  1.0
d  1.0  2.0  2.0
e  0.0  1.0  2.0
f  0.0  2.0  0.0
g  0.0  2.0  1.0
h  0.0  2.0  0.0
q  0.0  0.0  1.0

In [68]:
# 결측치 처리
from numpy import nan as NA
data = Series([1, NA, 3.5, NA, 7])
data.dropna() # drop na은 drop NaN을 뜻하여 data에서 Na값들이 떨어져 나간 것을 볼 수 있습니다.

0    1.0
2    3.5
4    7.0
dtype: float64

In [69]:
# 같은 결과
#print(data.notnull())
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [70]:
df = DataFrame([[NA, 6.5, 3.], [NA, NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
df

    0    1    2
0 NaN  6.5  3.0
1 NaN  NaN  NaN
2 NaN  NaN  NaN
3 NaN  6.5  3.0

In [71]:
# 한 항목이라도 NA가 있으면 해당 행을 삭제한다
cleaned = df.dropna()
cleaned

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [72]:
# 행의 모든 항목이 NA일때 해당 행을 삭제한다
df.dropna(how='all')

    0    1    2
0 NaN  6.5  3.0
3 NaN  6.5  3.0

In [73]:
df

    0    1    2
0 NaN  6.5  3.0
1 NaN  NaN  NaN
2 NaN  NaN  NaN
3 NaN  6.5  3.0

In [74]:
# 컬럼에 대한 삭제시는 axis=1을 사용한다
clean2 = df.dropna(axis=1)
clean2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [75]:
clean2 = df.dropna(axis=1, how='all')
clean2

     1    2
0  6.5  3.0
1  NaN  NaN
2  NaN  NaN
3  6.5  3.0

In [76]:
df = DataFrame(np.random.randn(7 , 3))
df.iloc[:4, 1] = NA 
df.iloc[:2, 2] = NA
df.iloc[0,0] = NA
df

          0         1         2
0       NaN       NaN       NaN
1  0.526774       NaN       NaN
2 -0.320869       NaN  0.695594
3  1.385647       NaN  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

In [77]:
df.dropna(thresh=2) # Keep only the rows with at least 2 non-NA values.

          0         1         2
2 -0.320869       NaN  0.695594
3  1.385647       NaN  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

In [78]:
df

          0         1         2
0       NaN       NaN       NaN
1  0.526774       NaN       NaN
2 -0.320869       NaN  0.695594
3  1.385647       NaN  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

In [79]:
# 컬럼별로 다른 값을 채울 수 있다. 사전을 사용한다
df.fillna({1: 0.5, 2: -1})

          0         1         2
0       NaN  0.500000 -1.000000
1  0.526774  0.500000 -1.000000
2 -0.320869  0.500000  0.695594
3  1.385647  0.500000  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

In [80]:
df # fillna()로 내용은 바뀌지 않는다.

          0         1         2
0       NaN       NaN       NaN
1  0.526774       NaN       NaN
2 -0.320869       NaN  0.695594
3  1.385647       NaN  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

In [81]:
# 새로운 변수를 정의하면 바뀐 값을 얻는다
df2 = df.fillna({1: 0.5, 2: -1})
df2

          0         1         2
0       NaN  0.500000 -1.000000
1  0.526774  0.500000 -1.000000
2 -0.320869  0.500000  0.695594
3  1.385647  0.500000  0.132477
4 -0.409024  1.562363 -0.073574
5  0.170118  0.790747  0.763853
6  0.398613 -0.358327 -0.177908

## concatenation
- concat 명령을 사용하면 기준 열(key column)을 사용하지 않고 단순히 데이터를 연결(concatenate)한다.
- 기본적으로는 위/아래로 데이터 행을 연결한다. 단순히 두 시리즈나 데이터프레임을 연결하기 때문에 인덱스 값이 중복될 수 있다.

In [82]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [83]:
df2 = pd.DataFrame(np.ones((3,4)))
df2

     0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [84]:
pd.concat([df1,df2])

     0    1     2     3
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
0  1.0  1.0   1.0   1.0
1  1.0  1.0   1.0   1.0
2  1.0  1.0   1.0   1.0

In [85]:
pd.concat([df1,df2], axis=1)

   0  1   2   3    0    1    2    3
0  0  1   2   3  1.0  1.0  1.0  1.0
1  4  5   6   7  1.0  1.0  1.0  1.0
2  8  9  10  11  1.0  1.0  1.0  1.0

## Merge

In [86]:
df1 = pd.DataFrame({
    '고객번호': [1001, 1002, 1003, 1004],
    '이름': ['A', 'B', 'C', 'D']
})
df1

   고객번호 이름
0  1001  A
1  1002  B
2  1003  C
3  1004  D

In [87]:
df2 = pd.DataFrame({
    '고객번호': [1001, 1001, 1002, 1006],
    '금액': [10000, 20000, 15000, 5000]
})
df2

   고객번호     금액
0  1001  10000
1  1001  20000
2  1002  15000
3  1006   5000

In [88]:
pd.merge(df1, df2)   # 공통인 열을 찾아 합친다 (inner join)

   고객번호 이름     금액
0  1001  A  10000
1  1001  A  20000
2  1002  B  15000

In [89]:
pd.merge(df1, df2, how='outer') # 키 값이 한쪽에만 있어도 보여줌 (outer join)

   고객번호   이름       금액
0  1001    A  10000.0
1  1001    A  20000.0
2  1002    B  15000.0
3  1003    C      NaN
4  1004    D      NaN
5  1006  NaN   5000.0

In [90]:
pd.merge(df1, df2, how='left')  # 첫번째 데이터프레임의 키 값을 모두 보여준다

   고객번호 이름       금액
0  1001  A  10000.0
1  1001  A  20000.0
2  1002  B  15000.0
3  1003  C      NaN
4  1004  D      NaN

In [91]:
pd.merge(df1, df2, how='right') # 두번째 데이터프레임의 키 값을 모두 보여준다

   고객번호   이름     금액
0  1001    A  10000
1  1001    A  20000
2  1002    B  15000
3  1006  NaN   5000

In [92]:
# join method 를 사용할 수도 있다.
df1 = df1.set_index('고객번호')
df2 = df2.set_index('고객번호')
df1

     이름
고객번호
1001  A
1002  B
1003  C
1004  D

In [93]:
df2

         금액
고객번호
1001  10000
1001  20000
1002  15000
1006   5000

In [94]:
df1.join(df2)

     이름       금액
고객번호
1001  A  10000.0
1001  A  20000.0
1002  B  15000.0
1003  C      NaN
1004  D      NaN

In [95]:
df1.join(df2, how='outer')

       이름       금액
고객번호
1001    A  10000.0
1001    A  20000.0
1002    B  15000.0
1003    C      NaN
1004    D      NaN
1006  NaN   5000.0